Braaanch
Artorias-theMindful/NotificationServiceBackEnd pull request #1
Opened 2023-11-22 08:08 UTC by Artorias-theMindful

please check

2024-01-23 22:25 UTC, LuneLink commented
1) There is no splliting by "layers" Everything mixing which is not good (try to use MVC  where MODEL -> servicess entities , repos etc.)
2) no tsconfig
3) Entity is strongly wired with db and also depends on knex find the way to break this dependency
4) There are some imports which is did nothing 
5) You need to care about code style

2024-01-23 22:25 UTC, LuneLink requested changes

2024-01-23 22:25 UTC, LuneLink commented on package.json
> +    "dotenv": "^16.3.1",
should it be part of dependency and why ?

2024-01-23 22:25 UTC, LuneLink commented on src/app.ts
> +declare var require: any
why do you need it ?

2024-01-23 22:25 UTC, LuneLink commented on src/app.ts
> +import { config as dotenvConfig } from 'dotenv';
is there better approach to populate envs?

2024-01-23 22:25 UTC, LuneLink commented on src/app.ts
> +dotenvConfig({ path: path.resolve(__dirname, '../.env') });
.env is not in the .gitignore

2024-01-23 22:25 UTC, LuneLink commented on src/app.ts
> +    userOptions.createUser(req.body)
you may get 200 earlier than operation complete
you may have unsuccessfully operation and status 200 which is incorrect

2024-01-23 22:25 UTC, LuneLink commented on src/db/knexfile.ts
> +  staging: {
do you have staging and prod ?

2024-01-23 22:25 UTC, LuneLink commented on src/entities/notification.ts
> +import express, { Request, Response } from "express";
do you need to have it here ?

2024-01-23 22:25 UTC, LuneLink commented on src/entities/user.ts
> +    async createUser(props: UserProps){
why do vou need async here ?

2024-01-23 22:25 UTC, LuneLink commented on src/app.ts
> +  .route('/users/:userId/notifications/:notificationId')
no any reason to have info about user to get notification

2024-01-23 22:25 UTC, LuneLink commented on src/app.ts
> +      const data = await userOptions.getUsersExceptChosen(Number(req.params.id))
here can be small optimization

2024-01-26 23:07 UTC, Artorias-theMindful commented on package.json
> +    "dotenv": "^16.3.1",
i have no idea why it shouldn't be because othervise my process.env variables are undefined

2024-01-27 19:55 UTC, LuneLink commented on package.json
> +    "dotenv": "^16.3.1",
NodeJs can use Environment variable, 
On the cloud you probabaly will not have .env file but you will have operation system envs so you need to have common solution 
right now your business relay on dotenv but actually your buissiness logic should't
1) such deps SHOULD be in the devDependencies section because they are Only for development but not for prod
2) check `node -r` and `dotenv` doc to find the way to populate envs not in the code

2024-01-30 18:46 UTC, Artorias-theMindful commented on package.json
> +    "dotenv": "^16.3.1",
so process.env variables should be forsaken in the code and i have to try something else? or is it allowed to use the following code in config.ts file:
`import dotenv from 'dotenv';
dotenv.config();
export const CONFIG = {
    DATABASE_URL: process.env.URL,
    PORT: process.env.PORT
  }`

2024-01-30 19:05 UTC, LuneLink commented on package.json
> +    "dotenv": "^16.3.1",
Your NodeJS application may get env not only from .env file 
But Your solution assumes to have .env file which is not correct

2024-02-04 09:35 UTC, LuneLink approved these changes

2024-02-04 10:55 UTC, merged